### ISSUE TITLE
Trigger threshold in the DAQ

### ISSUE THREAD

**Issue by ekneale** [AIT-WATCHMAN/rat-pac#103]
The trigger in LessSimpleDAQProc is currently the time of the first hit in a sub event. Perhaps we should think about introducing a trigger threshold into the DAQ.

This would also help with issue #97 where we are getting a lot of re-triggers in the veto due to the tyvek. In looking into pull request #102 I found a that all of the re-triggers (with the fix to equate the time windows) had <4 hits so these re-triggers would probably be removed by a threshold.

I can implement this if others are in agreement.

**Comment by feliciasutanto** [comment]
Ah this looks like something we need to discuss with the daq people..? 
Are we planning to use L1 trigger in watchman (for example grouping pmts into a group of 4 like in watchboy)?
If so, I think Liz's suggestion makes sense because such trigger needs to be introduced before bonsai reconstructs the event.

Btw, it seems like the multiple subevents problem happens only in veto volume. 
Since  we're not using veto pmts to reconstruct event, is it perhaps ok to let veto pmts have  multiple subevents..?
